server:
  port: 8080

spring:
  mail:
    host: ${MAIL.HOST}
    username: ${MAIL.USER}
    password: ${MAIL.PASSWORD}
    properties: 
      mail:
        smtp: 
          auth: true
          socketFactory:
            port: ${MAIL.PORT}
            fallback: false

security:
  basic: 
    enabled: false
  user: 
    name: ${MAIL.USER}
    password: ${MAIL.PASSWORD}

endpoints:
  autoconfig:
    enabled: false
  beans:
    enabled: false
  configprops:
    enabled: false
  dump:
    enabled: false

logging:
    file: /root/logs/application.log

---

spring:
    profiles: development
server:
  port: 9002

---

spring:
    profiles: test
server:
  port: 9001

---

spring:
    profiles: release
server:
  port: 9000
